# Generated by Django 5.2.6 on 2025-09-14 08:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='discount_for_product_category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='category', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='img_name', unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='username', unique=True),
        ),
    ]
