# Generated by Django 5.2.6 on 2025-09-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_price',
        ),
    ]
