# Generated by Django 5.2.6 on 2025-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Конечная цена'),
        ),
    ]
