# Generated by Django 5.2.6 on 2025-09-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='last_price',
        ),
    ]
